title: kansaspattons.org
email: jeffrey@kansaspattons.org
description: >-
baseurl: "/kansaspattons"
url: "https://jeffpatton1971.github.io"
author: "Jeff Patton"

show_excerpts: true

paginate: 10
paginate_path: /posts/page:num
permalink: /blog/:year/:month/:day/:title.html

collections:
  gallery:
    sort_by: taken_at
    output: true

header_pages:
  - posts.md
  - galleries.html

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

minima:
  skin: dirt
  social_links:
    github: jeffpatton1971
    linkedin: jeffpatton

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache