title: kansaspattons.org
email: jeffrey@kansaspattons.org
description: >-
baseurl: "/kansaspattons"
url: "https://jeffpatton1971.github.io"
author: "Jeff Patton"

show_excerpts: true

paginate: 5
paginate_path: /posts/page:num

collections:
  gallery:
    sort_by: taken_at
    output: true

header_pages:
  - posts.md
  - galleries.html

markdown: kramdown
theme: minima

minima:
  skin: solarized
  social_links:
    github: jeffpatton1971
    linkedin: jeffpatton

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate